### ISSUE TITLE
Can we rename this repo to "community"?

### ISSUE THREAD

**Issue by technosophos** [cnabio/community#10]
Since there are no code dependencies, I think we can do this without risk of breakages. And GitHub should do the redirect, IIRC.

**Comment by carolynvs** [comment]
Sounds good to me, we may have some links to the meeting-notes/contribution ladder but like you said, GH will redirect.

**Comment by carolynvs** [comment]
New year new you. Let's rename this!

**Comment by flynnduism** [comment]
That makes ~~cnab-sense~~ sense

**Comment by carolynvs** [comment]
Done!
